# Generated by Django 3.2.12 on 2022-06-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.subcategory'),
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue')], default='', max_length=255, unique=True)),
                ('S', models.BooleanField(default=True)),
                ('M', models.BooleanField(default=True)),
                ('L', models.BooleanField(default=True)),
                ('XL', models.BooleanField(default=True)),
                ('DXL', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.product', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='colorVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('White', models.BooleanField(default=True)),
                ('Black', models.BooleanField(default=True)),
                ('Blue', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.product', unique=True)),
            ],
        ),
    ]
