# Generated by Django 3.2.12 on 2022-06-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20220620_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.product'),
        ),
    ]
