# Generated by Django 3.2.12 on 2022-06-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_varient_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.product'),
        ),
    ]
