# Generated by Django 3.2.12 on 2022-06-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_varient_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='product',
        ),
    ]
