# Generated by Django 3.2.12 on 2022-06-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Varient',
        ),
    ]
