# Generated by Django 3.2.12 on 2022-06-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_delete_varient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue')], default='', max_length=255)),
                ('S', models.BooleanField(default=True)),
                ('M', models.BooleanField(default=True)),
                ('L', models.BooleanField(default=True)),
                ('XL', models.BooleanField(default=True)),
                ('DXL', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.product', unique=True)),
            ],
        ),
    ]
