# Generated by Django 3.2.12 on 2022-06-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='Black',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Blue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='White',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='colorVarient',
        ),
    ]
