# Generated by Django 3.2.12 on 2022-06-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20220620_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Varient',
        ),
        migrations.AddField(
            model_name='product',
            name='DXL',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='L',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='M',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='S',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='XL',
            field=models.BooleanField(default=True),
        ),
    ]
