# Generated by Django 3.2.12 on 2022-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_auto_20220621_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='filtersize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='', max_length=255)),
                ('top', models.CharField(max_length=10)),
                ('left', models.CharField(max_length=10)),
                ('hight', models.CharField(max_length=10)),
                ('width', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
