# Generated by Django 3.2.12 on 2022-06-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_auto_20220621_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtersize',
            old_name='size',
            new_name='name',
        ),
    ]
