# Generated by Django 3.2.12 on 2022-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersize',
            name='hight',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='filtersize',
            name='width',
            field=models.IntegerField(max_length=10),
        ),
    ]
