# Generated by Django 3.2.12 on 2022-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_auto_20220621_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersize',
            name='hight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filtersize',
            name='width',
            field=models.IntegerField(),
        ),
    ]
