# Generated by Django 3.2.12 on 2022-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_order_customize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_customize',
            name='image1',
            field=models.FileField(null=True, upload_to='media/customtees/%y/%m/'),
        ),
    ]
