# Generated by Django 3.2.12 on 2022-07-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_alter_order_customize_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_customize',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='order_customize',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='order_customize',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='order_customize',
            name='timage1',
        ),
        migrations.RemoveField(
            model_name='order_customize',
            name='timage2',
        ),
        migrations.RemoveField(
            model_name='order_customize',
            name='timage3',
        ),
        migrations.CreateModel(
            name='Order_customize_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webpages.order_customize')),
            ],
        ),
    ]
