# Generated by Django 3.2.12 on 2022-07-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_auto_20220702_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_customize_photo',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order_customize',
        ),
        migrations.DeleteModel(
            name='Order_customize_photo',
        ),
    ]
