# Generated by Django 3.2.12 on 2022-07-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0021_auto_20220717_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_colors', to='webpages.Color'),
        ),
    ]
