# Generated by Django 3.2.12 on 2022-07-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0022_alter_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
