# Generated by Django 3.2.12 on 2022-07-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0025_product_imagedrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/tees/%y/%m/')),
                ('S', models.BooleanField(default=True)),
                ('M', models.BooleanField(default=True)),
                ('L', models.BooleanField(default=True)),
                ('XL', models.BooleanField(default=True)),
                ('DXL', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Black',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Blue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='DXL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='L',
        ),
        migrations.RemoveField(
            model_name='product',
            name='M',
        ),
        migrations.RemoveField(
            model_name='product',
            name='S',
        ),
        migrations.RemoveField(
            model_name='product',
            name='White',
        ),
        migrations.RemoveField(
            model_name='product',
            name='XL',
        ),
    ]
