# Generated by Django 3.2.14 on 2022-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0026_auto_20220726_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='DXL',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='L',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='M',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='S',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='XL',
        ),
        migrations.RemoveField(
            model_name='featuredproduct',
            name='color',
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='sizefeatured',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_size', to='webpages.Size'),
        ),
    ]
