# Generated by Django 3.2.14 on 2022-08-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0027_auto_20220801_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
