# Generated by Django 3.2.14 on 2022-08-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0028_delete_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_thought', models.CharField(max_length=100)),
            ],
        ),
    ]
