# Generated by Django 3.2.14 on 2022-08-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0031_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
