# Generated by Django 3.2.14 on 2022-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0034_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='disigncolor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='black', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tshirtcolor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='black', max_length=255),
        ),
    ]
