# Generated by Django 3.2.14 on 2022-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0035_auto_20220807_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='', max_length=255),
        ),
    ]
