# Generated by Django 3.2.14 on 2022-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0038_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersize',
            name='name',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('logo', 'logo'), ('small', 'small'), ('topcenter', 'topcenter'), ('bottom', 'bottom'), ('bottomleft', 'bottomleft'), ('bottomright', 'bottomright')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('logo', 'logo'), ('small', 'small'), ('topcenter', 'topcenter'), ('bottom', 'bottom'), ('bottomleft', 'bottomleft'), ('bottomright', 'bottomright')], default='large', max_length=255),
        ),
    ]
