# Generated by Django 3.2.14 on 2022-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0039_auto_20220808_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disigncolor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='white', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='tshirtcolor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='white', max_length=255),
        ),
    ]
