# Generated by Django 3.2.14 on 2022-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0041_auto_20220814_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersize',
            name='name',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('logo', 'logo'), ('small', 'small'), ('mediumless', 'mediumless'), ('hightless', 'hightless'), ('topcenter', 'topcenter'), ('bottom', 'bottom'), ('bottomleft', 'bottomleft'), ('bottomright', 'bottomright')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('logo', 'logo'), ('small', 'small'), ('mediumless', 'mediumless'), ('hightless', 'hightless'), ('topcenter', 'topcenter'), ('bottom', 'bottom'), ('bottomleft', 'bottomleft'), ('bottomright', 'bottomright')], default='large', max_length=255),
        ),
    ]
