# Generated by Django 3.2.14 on 2022-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0047_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actualprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
