# Generated by Django 3.2.14 on 2022-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0049_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happycustomer',
            name='customer_thought',
            field=models.CharField(max_length=1000),
        ),
    ]
