# Generated by Django 3.2.12 on 2022-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id_char', models.CharField(default='', max_length=255)),
                ('items_json', models.CharField(max_length=5000)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('total_items', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.CharField(default='', max_length=200)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Out for delivery', 'Out for delivery'), ('Mid Way', 'Mid Way'), ('Delivered', 'Delivered')], default='Order Recieved', max_length=100)),
                ('payment', models.CharField(choices=[('razorpay', 'razorpay'), ('cash', 'cash')], default='', max_length=255)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING'), (4, 'PENDING CASH'), (5, 'Order cancelled and refund processed')], default=3)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
