# Generated by Django 3.2.12 on 2022-06-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20220622_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_items',
        ),
    ]
