# Generated by Django 3.2.12 on 2022-06-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20220622_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
