# Generated by Django 3.2.12 on 2022-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('items_json', models.CharField(max_length=5000)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING'), (4, 'PENDING CASH'), (5, 'Order cancelled and refund processed')], default=3)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
