# Generated by Django 3.2.12 on 2022-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='made_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
