# Generated by Django 3.2.12 on 2022-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='t_image',
            field=models.TextField(default=''),
        ),
    ]
