# Generated by Django 3.2.12 on 2022-07-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_order_t_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='t_image',
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/tees/%y/%m/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Cart.order')),
            ],
        ),
    ]
