# Generated by Django 3.2.12 on 2022-07-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_rename_lesson_orderphoto_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderphoto',
            name='photo',
            field=models.TextField(),
        ),
    ]
