# Generated by Django 3.2.12 on 2022-07-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_alter_orderphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
