# Generated by Django 3.2.14 on 2022-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_alter_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('prepaid', 'prepaid'), ('cod', 'cod')], default='', max_length=255),
        ),
    ]
