# Generated by Django 3.2.14 on 2022-08-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
